// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package http

import (
	"net/http"
	"sync"
)

// Ensure, that DoerMock does implement Doer.
// If this is not the case, regenerate this file with moq.
var _ Doer = &DoerMock{}

// DoerMock is a mock implementation of Doer.
//
//	func TestSomethingThatUsesDoer(t *testing.T) {
//
//		// make and configure a mocked Doer
//		mockedDoer := &DoerMock{
//			DoFunc: func(request *http.Request) (*http.Response, error) {
//				panic("mock out the Do method")
//			},
//		}
//
//		// use mockedDoer in code that requires Doer
//		// and then make assertions.
//
//	}
type DoerMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(request *http.Request) (*http.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Request is the request argument value.
			Request *http.Request
		}
	}
	lockDo sync.RWMutex
}

// Do calls DoFunc.
func (mock *DoerMock) Do(request *http.Request) (*http.Response, error) {
	if mock.DoFunc == nil {
		panic("DoerMock.DoFunc: method is nil but Doer.Do was just called")
	}
	callInfo := struct {
		Request *http.Request
	}{
		Request: request,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(request)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedDoer.DoCalls())
func (mock *DoerMock) DoCalls() []struct {
	Request *http.Request
} {
	var calls []struct {
		Request *http.Request
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}
